from __future__ import annotations

from dataclasses import dataclass
from typing import Dict

DEFAULT_LANGUAGE = "pl"

SUPPORTED_LANGUAGES: Dict[str, Dict[str, object]] = {
    "pl": {"label": "Polski"},
    "en": {"label": "English"},
    "de": {"label": "Deutsch"},
    "es": {"label": "Español"},
    "pt": {"label": "Português"},
    "ru": {"label": "Русский"},
}

TRANSLATIONS: Dict[str, Dict[str, str]] = {
    "pl": {
        "menu.banner": "\n╔══════════════════════════════════════╗\n║        ⏰ Steam Hour Booster         ║\n╚══════════════════════════════════════╝",
        "menu.section_main": "[Menu główne]",
        "menu.status": "Konto: {account}   Gry: {games}",
        "menu.status.account_ok": "gotowe",
        "menu.status.account_missing": "brak danych",
        "menu.option.account": "Konfiguracja konta",
        "menu.option.games": "Konfiguracja gier",
        "menu.option.run": "Uruchom",
        "menu.option.exit": "Wyjdź",
        "menu.option.language": "Zmień język",
        "prompt.choose_option": "\nWybierz opcję: ",
        "general.unknown_option": "Nieznana opcja.",
        "general.interrupted_exit": "Przerwano. Wyłączam program.",
        "general.interrupted_back": "Przerwano. Powrót do menu głównego.",
        "general.cancelled": "Przerwano.",
        "general.goodbye": "Do zobaczenia!",
        "general.back": "Powrót",
        "general.not_set": "[nie ustawiono]",
        "general.error": "Błąd: {message}",
        "language.initial_title": "Wybierz język interfejsu",
        "language.initial_instruction": "Ta konfiguracja zostanie zapisana w pliku config.json.",
        "language.prompt": "Podaj numer języka: ",
        "language.invalid": "Nieprawidłowy numer języka.",
        "language.saved": "Zapisano język: {language}",
        "language.list.entry": "{index}. [{marker}] {label} ({code})",
        "account.menu_title": "Konto Steam – menu",
        "account.menu_banner": "\n╔══════════════════════╗\n║  Konto Steam – menu  ║\n╚══════════════════════╝",
        "account.option.summary": "Podgląd danych",
        "account.option.username": "Ustaw login",
        "account.option.password": "Ustaw hasło",
        "account.option.secret": "Ustaw shared_secret (2FA)",
        "account.option.reset": "Reset całej konfiguracji",
        "account.option.language": "Zmień język interfejsu",
        "account.option.api_key": "Ustaw Steam Web API Key",
        "account.option.steam_id": "Ustaw SteamID64",
        "account.summary.title": "--- Konto Steam ---",
        "account.summary.login": "Login: {value}",
        "account.summary.password": "Hasło: {value}",
        "account.summary.secret": "Shared secret: {value}",
        "account.summary.secret_set": "ustawiono",
        "account.summary.secret_missing": "brak",
        "account.prompt.username": "Podaj login Steam: ",
        "account.error.username_required": "Login nie może być pusty.",
        "account.saved.username": "Zapisano login.",
        "account.prompt.password": "Podaj hasło Steam: ",
        "account.error.password_required": "Hasło nie może być puste.",
        "account.saved.password": "Zapisano hasło.",
        "account.prompt.secret": "Podaj shared_secret z aplikacji mobilnej (Enter aby usunąć): ",
        "account.saved.secret": "Zaktualizowano shared_secret.",
        "account.error.api_key_required": "API key nie może być pusty.",
        "account.prompt.api_key": "Podaj Steam Web API Key (https://steamcommunity.com/dev/apikey): ",
        "account.saved.api_key": "Zapisano API key.",
        "account.prompt.steam_id": "Podaj SteamID64 (np. 76561198...): ",
        "account.error.steam_id_required": "SteamID64 jest wymagane.",
        "account.saved.steam_id": "Zapisano SteamID64.",
        "account.reset.confirm": "Reset usunie login/hasło. Kontynuować? ({yes}/N): ",
        "account.reset.done": "Przywrócono domyślną konfigurację.",
        "account.language.changed": "Zmieniono język na: {language}",
        "games.menu_title": "Gry – konfiguracja",
        "games.menu_banner": "\n╔══════════════════════╗\n║  Gry – konfiguracja  ║\n╚══════════════════════╝",
        "games.option.list": "Lista AppID",
        "games.option.add": "Dodaj AppID gry",
        "games.option.remove": "Usuń AppID gry",
        "games.option.clear": "Wyczyść listę gier",
        "games.option.library": "Dodaj z biblioteki Steam",
        "games.summary.empty": "--- Gry ---\nBrak dodanych AppID.",
        "games.summary.title": "--- Gry ---",
        "games.summary.count": "Liczba gier: {count} / {max}",
        "games.summary.items": "AppID-y: {items}",
        "games.list.current_none": "Brak dodanych AppID.",
        "games.list.current": "Aktualne AppID: {items}",
        "games.error.full": "Lista gier jest pełna.",
        "games.prompt.add": "Podaj AppID gry (liczba): ",
        "games.error.appid_integer": "AppID musi być liczbą całkowitą.",
        "games.error.appid_positive": "AppID musi być dodatnie.",
        "games.error.appid_exists": "AppID już znajduje się na liście.",
        "games.added": "Dodano AppID.",
        "games.prompt.remove": "Podaj AppID do usunięcia: ",
        "games.error.appid_missing": "AppID nie znajduje się na liście.",
        "games.removed": "Usunięto AppID.",
        "games.prompt.clear_confirm": "Na pewno chcesz usunąć wszystkie gry? ({yes}/N): ",
        "games.cleared": "Wyczyszczono listę gier.",
        "library.fetching": "Pobieram bibliotekę gier ze Steam...",
        "library.error.credentials": "Uzupełnij API key (https://steamcommunity.com/dev/apikey) w konfiguracji konta.",
        "library.prompt.vanity": "Podaj nazwę profilu Steam (vanity URL), aby automatycznie pobrać SteamID64: ",
        "library.error.vanity_lookup": "Nie udało się ustalić SteamID na podstawie nazwy: {reason}",
        "library.error.request": "Nie udało się pobrać listy gier: {reason}",
        "library.empty": "Biblioteka gier jest pusta.",
        "library.prompt.selection": "Podaj numery gier do dodania (np. 1,3,5) lub Enter aby anulować: ",
        "library.selection.invalid": "Nieprawidłowy wybór: {value}",
        "library.selection.out_of_range": "Numer poza zakresem: {value}",
        "library.selection.none": "Nie wybrano żadnej gry.",
        "library.added": "Dodano z biblioteki: {count} gier.",
        "library.legend.existing": "[*] Gra oznaczona gwiazdką jest już dodana do listy gier.",
        "library.error.steam_id_missing": "Najpierw ustaw SteamID64.",
        "library.resolved.steam_id": "Ustalono SteamID64: {steam_id}",
        "start.title": "=== ⏰ Start programu Steam ===",
        "start.account": "Konto: {username}",
        "start.games": "Gry do uruchomienia: {count}",
        "start.finished": "⏰ Booster zatrzymany.",
        "errors.missing_username": "Brakuje nazwy użytkownika Steam.",
        "errors.missing_password": "Brakuje hasła Steam.",
        "errors.missing_games": "Dodaj co najmniej jeden AppID gry.",
        "steam.preparing": "[Steam] Przygotowuję uruchomienie {count} gier: {games}",
        "steam.connecting": "[Steam] Łączenie z kontem...",
        "steam.launched": "[Steam] Uruchomiono gry: {games}",
        "steam.prompt.stop": "⏰ Wciśnij Enter lub Ctrl+C, aby zatrzymać program...\n",
        "steam.running": "⏰ Booster działa.",
        "steam.clock": "⏰ Nabity łączny czas: {time}",
        "steam.login.success": "Pomyślnie zalogowano.",
        "steam.login.email_needed": "[Steam] Wymagany kod z e-mail (Steam Guard).",
        "steam.login.email_prompt": "Kod z e-mail (Steam Guard): ",
        "steam.login.twofactor_needed": "[Steam] Wymagany kod z aplikacji Steam Guard.",
        "steam.login.twofactor_prompt": "Kod z aplikacji mobilnej Steam: ",
        "steam.login.invalid_password_prompt": "[Steam] Błędne hasło, spróbuj ponownie.",
        "steam.login.invalid_password_input": "Błędne hasło. Podaj ponownie: ",
        "steam.login.credentials_missing": "Brakuje danych logowania.",
        "steam.login.error_generic": "Logowanie zakończone błędem: {result}",
        "steam.error.no_games": "Brak gier do uruchomienia.",
        "steam.interrupt": "Przerywam...",
        "steam.logout": "[Steam] Wylogowano ze Steam.",
        "steam.warning.persona_missing": "Nie znaleziono metody set_persona w kliencie Steam.",
    },
    "en": {
        "menu.section_main": "[Main menu]",
        "menu.status": "Account: {account}   Games: {games}",
        "menu.status.account_ok": "ready",
        "menu.status.account_missing": "missing",
        "menu.option.account": "Account configuration",
        "menu.option.games": "Games configuration",
        "menu.option.run": "Run",
        "menu.option.exit": "Exit",
        "menu.option.language": "Change language",
        "menu.banner": "\n╔══════════════════════════════════════╗\n║        ⏰ Steam Hour Booster         ║\n╚══════════════════════════════════════╝",
        "prompt.choose_option": "\nChoose an option: ",
        "general.unknown_option": "Unknown option.",
        "general.interrupted_exit": "Interrupted. Exiting program.",
        "general.interrupted_back": "Interrupted. Returning to main menu.",
        "general.cancelled": "Cancelled.",
        "general.goodbye": "See you!",
        "general.back": "Back",
        "general.not_set": "[not set]",
        "general.error": "Error: {message}",
        "language.initial_title": "Select interface language",
        "language.initial_instruction": "This preference will be saved inside config.json.",
        "language.prompt": "Enter language number: ",
        "language.invalid": "Invalid language number.",
        "language.saved": "Language saved: {language}",
        "language.list.entry": "{index}. [{marker}] {label} ({code})",
        "account.menu_title": "Steam account – menu",
        "account.menu_banner": "\n╔══════════════════════╗\n║  Steam account menu  ║\n╚══════════════════════╝",
        "account.option.summary": "Show summary",
        "account.option.username": "Set login",
        "account.option.password": "Set password",
        "account.option.secret": "Set shared_secret (2FA)",
        "account.option.reset": "Reset entire configuration",
        "account.option.language": "Change interface language",
        "account.option.api_key": "Set Steam Web API Key",
        "account.option.steam_id": "Set SteamID64",
        "account.summary.title": "--- Steam account ---",
        "account.summary.login": "Login: {value}",
        "account.summary.password": "Password: {value}",
        "account.summary.secret": "Shared secret: {value}",
        "account.summary.secret_set": "set",
        "account.summary.secret_missing": "not set",
        "account.prompt.username": "Enter Steam login: ",
        "account.error.username_required": "Login cannot be empty.",
        "account.saved.username": "Login saved.",
        "account.prompt.password": "Enter Steam password: ",
        "account.error.password_required": "Password cannot be empty.",
        "account.saved.password": "Password saved.",
        "account.prompt.secret": "Enter shared_secret from the mobile app (press Enter to clear): ",
        "account.saved.secret": "shared_secret updated.",
        "account.error.api_key_required": "API key cannot be empty.",
        "account.prompt.api_key": "Enter Steam Web API Key (https://steamcommunity.com/dev/apikey): ",
        "account.saved.api_key": "API key saved.",
        "account.prompt.steam_id": "Enter SteamID64 (e.g. 76561198...): ",
        "account.error.steam_id_required": "SteamID64 is required.",
        "account.saved.steam_id": "SteamID64 saved.",
        "account.reset.confirm": "Reset will remove login/password. Continue? ({yes}/N): ",
        "account.reset.done": "Configuration restored to defaults.",
        "account.language.changed": "Interface language changed to: {language}",
        "games.menu_title": "Games – configuration",
        "games.menu_banner": "\n╔══════════════════════╗\n║   Games settings     ║\n╚══════════════════════╝",
        "games.option.list": "List AppIDs",
        "games.option.add": "Add a game AppID",
        "games.option.remove": "Remove a game AppID",
        "games.option.clear": "Clear the list",
        "games.option.library": "Add from Steam library",
        "games.summary.empty": "--- Games ---\nNo AppIDs configured.",
        "games.summary.title": "--- Games ---",
        "games.summary.count": "Games: {count} / {max}",
        "games.summary.items": "AppIDs: {items}",
        "games.list.current_none": "No AppIDs configured.",
        "games.list.current": "Current AppIDs: {items}",
        "games.error.full": "The list of games is full.",
        "games.prompt.add": "Enter the game AppID (number): ",
        "games.error.appid_integer": "AppID must be an integer.",
        "games.error.appid_positive": "AppID must be positive.",
        "games.error.appid_exists": "AppID is already on the list.",
        "games.added": "AppID added.",
        "games.prompt.remove": "Enter the AppID to remove: ",
        "games.error.appid_missing": "AppID was not found on the list.",
        "games.removed": "AppID removed.",
        "games.prompt.clear_confirm": "Do you really want to remove all games? ({yes}/N): ",
        "games.cleared": "Game list cleared.",
        "library.fetching": "Fetching your Steam library...",
        "library.error.credentials": "Please fill in your API key (https://steamcommunity.com/dev/apikey) in the account settings.",
        "library.prompt.vanity": "Enter your Steam profile name (vanity URL) to resolve SteamID64: ",
        "library.error.vanity_lookup": "Failed to resolve SteamID from profile name: {reason}",
        "library.error.request": "Failed to fetch games: {reason}",
        "library.empty": "Your library is empty.",
        "library.prompt.selection": "Enter numbers to add (e.g. 1,3,5) or press Enter to cancel: ",
        "library.selection.invalid": "Invalid selection: {value}",
        "library.selection.out_of_range": "Selection out of range: {value}",
        "library.selection.none": "No games selected.",
        "library.added": "Added {count} games from the library.",
        "library.legend.existing": "[*] A starred game is already on the list.",
        "library.error.steam_id_missing": "Set your SteamID64 first.",
        "library.resolved.steam_id": "Resolved SteamID64: {steam_id}",
        "start.title": "=== ⏰ Starting Steam booster ===",
        "start.account": "Account: {username}",
        "start.games": "Games to launch: {count}",
        "start.finished": "⏰ Booster stopped.",
        "errors.missing_username": "Steam login is missing.",
        "errors.missing_password": "Steam password is missing.",
        "errors.missing_games": "Add at least one AppID.",
        "steam.preparing": "[Steam] Preparing to launch {count} games: {games}",
        "steam.connecting": "[Steam] Connecting to the account...",
        "steam.launched": "[Steam] Games launched: {games}",
        "steam.prompt.stop": "⏰ Press Enter or Ctrl+C to stop the program...\n",
        "steam.running": "⏰ Booster is running.",
        "steam.clock": "⏰ Total accumulated time: {time}",
        "steam.login.success": "Logged in successfully.",
        "steam.login.email_needed": "[Steam] E-mail (Steam Guard) code required.",
        "steam.login.email_prompt": "Steam Guard e-mail code: ",
        "steam.login.twofactor_needed": "[Steam] Steam Guard mobile code required.",
        "steam.login.twofactor_prompt": "Steam Guard mobile code: ",
        "steam.login.invalid_password_prompt": "[Steam] Wrong password, try again.",
        "steam.login.invalid_password_input": "Wrong password. Enter again: ",
        "steam.login.credentials_missing": "Login data is missing.",
        "steam.login.error_generic": "Login failed with error: {result}",
        "steam.error.no_games": "No games to launch.",
        "steam.interrupt": "Stopping...",
        "steam.logout": "[Steam] Logged out.",
        "steam.warning.persona_missing": "Could not find set_persona method in Steam client.",
    },
    "de": {
        "menu.banner": "\n╔══════════════════════════════════════╗\n║        ⏰ Steam Hour Booster         ║\n╚══════════════════════════════════════╝",
        "menu.section_main": "[Hauptmenü]",
        "menu.status": "Konto: {account}   Spiele: {games}",
        "menu.status.account_ok": "bereit",
        "menu.status.account_missing": "keine Daten",
        "menu.option.account": "Konto konfigurieren",
        "menu.option.games": "Spiele konfigurieren",
        "menu.option.language": "Sprache ändern",
        "menu.option.run": "Starten",
        "menu.option.exit": "Beenden",
        "prompt.choose_option": "\nOption wählen: ",
        "general.unknown_option": "Unbekannte Option.",
        "general.interrupted_exit": "Abgebrochen. Programm wird beendet.",
        "general.interrupted_back": "Abgebrochen. Zurück zum Hauptmenü.",
        "general.cancelled": "Abgebrochen.",
        "general.goodbye": "Bis bald!",
        "general.back": "Zurück",
        "general.not_set": "[nicht gesetzt]",
        "general.error": "Fehler: {message}",
        "language.initial_title": "Sprache auswählen",
        "language.initial_instruction": "Diese Einstellung wird in config.json gespeichert.",
        "language.prompt": "Sprachnummer eingeben: ",
        "language.invalid": "Ungültige Sprachnummer.",
        "language.saved": "Sprache gespeichert: {language}",
        "language.list.entry": "{index}. [{marker}] {label} ({code})",
        "account.menu_banner": "\n╔══════════════════════╗\n║  Steam-Konto – Menü  ║\n╚══════════════════════╝",
        "account.option.summary": "Daten anzeigen",
        "account.option.username": "Login setzen",
        "account.option.password": "Passwort setzen",
        "account.option.secret": "shared_secret setzen (2FA)",
        "account.option.reset": "Konfiguration zurücksetzen",
        "account.option.language": "Sprache ändern",
        "account.option.api_key": "Steam Web API Key setzen",
        "account.option.steam_id": "SteamID64 setzen",
        "account.summary.title": "--- Steam-Konto ---",
        "account.summary.login": "Login: {value}",
        "account.summary.password": "Passwort: {value}",
        "account.summary.secret": "Shared secret: {value}",
        "account.summary.secret_missing": "nicht gesetzt",
        "account.prompt.username": "Steam-Login eingeben: ",
        "account.error.username_required": "Login darf nicht leer sein.",
        "account.saved.username": "Login gespeichert.",
        "account.prompt.password": "Steam-Passwort eingeben: ",
        "account.error.password_required": "Passwort darf nicht leer sein.",
        "account.saved.password": "Passwort gespeichert.",
        "account.prompt.secret": "shared_secret aus der App eingeben (Enter zum Löschen): ",
        "account.saved.secret": "shared_secret aktualisiert.",
        "account.error.api_key_required": "API-Key darf nicht leer sein.",
        "account.prompt.api_key": "Steam Web API Key eingeben (https://steamcommunity.com/dev/apikey): ",
        "account.saved.api_key": "API-Key gespeichert.",
        "account.prompt.steam_id": "SteamID64 eingeben (z.B. 7656119...): ",
        "account.error.steam_id_required": "SteamID64 ist erforderlich.",
        "account.saved.steam_id": "SteamID64 gespeichert.",
        "account.reset.confirm": "Reset löscht Login/Passwort. Fortfahren? ({yes}/N): ",
        "account.reset.done": "Konfiguration zurückgesetzt.",
        "account.language.changed": "Sprache geändert zu: {language}",
        "games.menu_banner": "\n╔══════════════════════╗\n║  Spiele – Einstellungen ║\n╚══════════════════════╝",
        "games.option.list": "AppIDs anzeigen",
        "games.option.add": "AppID hinzufügen",
        "games.option.remove": "AppID entfernen",
        "games.option.clear": "Liste leeren",
        "games.option.library": "Aus Steam-Bibliothek hinzufügen",
        "games.summary.empty": "--- Spiele ---\nKeine AppIDs hinzugefügt.",
        "games.summary.title": "--- Spiele ---",
        "games.summary.count": "Spiele: {count} / {max}",
        "games.summary.items": "AppIDs: {items}",
        "games.error.full": "Spielliste ist voll.",
        "games.prompt.add": "AppID eingeben (Zahl): ",
        "games.error.appid_integer": "AppID muss eine ganze Zahl sein.",
        "games.error.appid_positive": "AppID muss positiv sein.",
        "games.error.appid_exists": "AppID ist bereits in der Liste.",
        "games.added": "AppID hinzugefügt.",
        "games.prompt.remove": "AppID zum Entfernen eingeben: ",
        "games.error.appid_missing": "AppID wurde nicht gefunden.",
        "games.removed": "AppID entfernt.",
        "games.prompt.clear_confirm": "Alle Spiele entfernen? ({yes}/N): ",
        "games.cleared": "Spielliste geleert.",
        "library.fetching": "Steam-Bibliothek wird abgerufen...",
        "library.error.credentials": "Bitte API-Key im Konto hinterlegen.",
        "library.prompt.vanity": "Profilnamen (Vanity URL) eingeben, um SteamID64 zu ermitteln: ",
        "library.error.vanity_lookup": "SteamID konnte nicht ermittelt werden: {reason}",
        "library.error.request": "Bibliothek konnte nicht geladen werden: {reason}",
        "library.empty": "Bibliothek ist leer.",
        "library.prompt.selection": "Nummern eingeben (z.B. 1,3,5) oder Enter zum Abbrechen: ",
        "library.selection.invalid": "Ungültige Auswahl: {value}",
        "library.selection.out_of_range": "Auswahl außerhalb des Bereichs: {value}",
        "library.selection.none": "Keine Spiele ausgewählt.",
        "library.added": "{count} Spiele aus Bibliothek hinzugefügt.",
        "library.legend.existing": "[*] Stern markiert bereits hinzugefügte Spiele.",
        "library.error.steam_id_missing": "Bitte zuerst SteamID64 setzen.",
        "library.resolved.steam_id": "SteamID64 ermittelt: {steam_id}",
        "start.title": "=== ⏰ Steam-Booster wird gestartet ===",
        "start.account": "Konto: {username}",
        "start.games": "Zu startende Spiele: {count}",
        "start.finished": "⏰ Booster gestoppt.",
        "errors.missing_username": "Steam-Login fehlt.",
        "errors.missing_password": "Steam-Passwort fehlt.",
        "errors.missing_games": "Mindestens eine AppID hinzufügen.",
        "steam.preparing": "[Steam] Bereite Start von {count} Spielen vor: {games}",
        "steam.connecting": "[Steam] Verbindung zum Konto...",
        "steam.launched": "[Steam] Spiele gestartet: {games}",
        "steam.prompt.stop": "⏰ Enter oder Ctrl+C zum Stoppen...\n",
        "steam.running": "⏰ Booster läuft.",
        "steam.clock": "⏰ Gesamtzeit: {time}",
        "steam.login.success": "Erfolgreich eingeloggt.",
        "steam.login.email_needed": "[Steam] E-Mail-Code (Steam Guard) erforderlich.",
        "steam.login.email_prompt": "E-Mail-Code eingeben: ",
        "steam.login.twofactor_needed": "[Steam] Mobil-Code erforderlich.",
        "steam.login.twofactor_prompt": "Mobilen Steam-Guard-Code eingeben: ",
        "steam.login.invalid_password_prompt": "[Steam] Falsches Passwort, erneut versuchen.",
        "steam.login.invalid_password_input": "Falsches Passwort. Erneut eingeben: ",
        "steam.login.credentials_missing": "Login-Daten fehlen.",
        "steam.login.error_generic": "Login fehlgeschlagen: {result}",
        "steam.error.no_games": "Keine Spiele zum Starten.",
        "steam.interrupt": "Abbruch...",
        "steam.logout": "[Steam] Abgemeldet.",
        "steam.warning.persona_missing": "set_persona-Methode nicht gefunden.",
    },
    "es": {
        "menu.banner": "\n╔══════════════════════════════════════╗\n║        ⏰ Steam Hour Booster         ║\n╚══════════════════════════════════════╝",
        "menu.section_main": "[Menú principal]",
        "menu.status": "Cuenta: {account}   Juegos: {games}",
        "menu.status.account_ok": "lista",
        "menu.status.account_missing": "sin datos",
        "menu.option.account": "Configurar cuenta",
        "menu.option.games": "Configurar juegos",
        "menu.option.language": "Cambiar idioma",
        "menu.option.run": "Iniciar",
        "menu.option.exit": "Salir",
        "prompt.choose_option": "\nElige una opción: ",
        "general.unknown_option": "Opción desconocida.",
        "general.interrupted_exit": "Interrumpido. Cerrando programa.",
        "general.interrupted_back": "Interrumpido. Volviendo al menú principal.",
        "general.cancelled": "Cancelado.",
        "general.goodbye": "¡Hasta luego!",
        "general.back": "Atrás",
        "general.not_set": "[no configurado]",
        "general.error": "Error: {message}",
        "language.initial_title": "Selecciona el idioma",
        "language.initial_instruction": "Esta preferencia se guardará en config.json.",
        "language.prompt": "Introduce el número del idioma: ",
        "language.invalid": "Número de idioma no válido.",
        "language.saved": "Idioma guardado: {language}",
        "language.list.entry": "{index}. [{marker}] {label} ({code})",
        "account.menu_banner": "\n╔══════════════════════╗\n║   Cuenta Steam       ║\n╚══════════════════════╝",
        "account.option.summary": "Mostrar datos",
        "account.option.username": "Configurar login",
        "account.option.password": "Configurar contraseña",
        "account.option.secret": "Configurar shared_secret (2FA)",
        "account.option.reset": "Restablecer configuración",
        "account.option.language": "Cambiar idioma",
        "account.option.api_key": "Configurar Steam Web API Key",
        "account.option.steam_id": "Configurar SteamID64",
        "account.summary.title": "--- Cuenta Steam ---",
        "account.summary.login": "Login: {value}",
        "account.summary.password": "Contraseña: {value}",
        "account.summary.secret": "Shared secret: {value}",
        "account.summary.secret_missing": "no configurado",
        "account.prompt.username": "Introduce el login de Steam: ",
        "account.error.username_required": "El login no puede estar vacío.",
        "account.saved.username": "Login guardado.",
        "account.prompt.password": "Introduce la contraseña de Steam: ",
        "account.error.password_required": "La contraseña no puede estar vacía.",
        "account.saved.password": "Contraseña guardada.",
        "account.prompt.secret": "Introduce el shared_secret de la app móvil (Enter para borrar): ",
        "account.saved.secret": "shared_secret actualizado.",
        "account.error.api_key_required": "La API key no puede estar vacía.",
        "account.prompt.api_key": "Introduce el Steam Web API Key (https://steamcommunity.com/dev/apikey): ",
        "account.saved.api_key": "API key guardada.",
        "account.prompt.steam_id": "Introduce SteamID64 (ej. 7656119...): ",
        "account.error.steam_id_required": "SteamID64 es obligatorio.",
        "account.saved.steam_id": "SteamID64 guardado.",
        "account.reset.confirm": "El reset borrará login/contraseña. ¿Continuar? ({yes}/N): ",
        "account.reset.done": "Configuración restaurada.",
        "account.language.changed": "Idioma cambiado a: {language}",
        "games.menu_banner": "\n╔══════════════════════╗\n║ Configuración juegos ║\n╚══════════════════════╝",
        "games.option.list": "Lista de AppID",
        "games.option.add": "Añadir AppID",
        "games.option.remove": "Eliminar AppID",
        "games.option.clear": "Vaciar lista",
        "games.option.library": "Añadir desde biblioteca",
        "games.summary.empty": "--- Juegos ---\nNo hay AppID configurados.",
        "games.summary.title": "--- Juegos ---",
        "games.summary.count": "Juegos: {count} / {max}",
        "games.summary.items": "AppID: {items}",
        "games.error.full": "La lista está llena.",
        "games.prompt.add": "Introduce el AppID del juego: ",
        "games.error.appid_integer": "El AppID debe ser un número entero.",
        "games.error.appid_positive": "El AppID debe ser positivo.",
        "games.error.appid_exists": "El AppID ya está en la lista.",
        "games.added": "AppID añadido.",
        "games.prompt.remove": "Introduce el AppID a eliminar: ",
        "games.error.appid_missing": "El AppID no está en la lista.",
        "games.removed": "AppID eliminado.",
        "games.prompt.clear_confirm": "¿Eliminar todos los juegos? ({yes}/N): ",
        "games.cleared": "Lista limpiada.",
        "library.fetching": "Obteniendo biblioteca de Steam...",
        "library.error.credentials": "Completa la API key en la configuración de la cuenta.",
        "library.prompt.vanity": "Introduce el nombre del perfil (vanity URL) para obtener el SteamID64: ",
        "library.error.vanity_lookup": "No se pudo obtener SteamID: {reason}",
        "library.error.request": "No se pudo obtener la biblioteca: {reason}",
        "library.empty": "La biblioteca está vacía.",
        "library.prompt.selection": "Introduce números (1,3,5) o Enter para cancelar: ",
        "library.selection.invalid": "Selección inválida: {value}",
        "library.selection.out_of_range": "Selección fuera de rango: {value}",
        "library.selection.none": "No se seleccionaron juegos.",
        "library.added": "Se añadieron {count} juegos.",
        "library.legend.existing": "[*] Ya está en la lista.",
        "library.error.steam_id_missing": "Primero configura el SteamID64.",
        "library.resolved.steam_id": "SteamID64 resuelto: {steam_id}",
        "start.title": "=== ⏰ Iniciando Steam booster ===",
        "start.account": "Cuenta: {username}",
        "start.games": "Juegos a iniciar: {count}",
        "start.finished": "⏰ Booster detenido.",
        "errors.missing_username": "Falta el login.",
        "errors.missing_password": "Falta la contraseña.",
        "errors.missing_games": "Añade al menos un AppID.",
        "steam.preparing": "[Steam] Preparando {count} juegos: {games}",
        "steam.connecting": "[Steam] Conectando con la cuenta...",
        "steam.launched": "[Steam] Juegos iniciados: {games}",
        "steam.prompt.stop": "⏰ Pulsa Enter o Ctrl+C para detener...\n",
        "steam.running": "⏰ Booster en marcha.",
        "steam.clock": "⏰ Tiempo total: {time}",
        "steam.login.success": "Inicio de sesión correcto.",
        "steam.login.email_needed": "[Steam] Se requiere código de email.",
        "steam.login.email_prompt": "Código del email: ",
        "steam.login.twofactor_needed": "[Steam] Se requiere código de Steam Guard.",
        "steam.login.twofactor_prompt": "Código de la app móvil: ",
        "steam.login.invalid_password_prompt": "[Steam] Contraseña incorrecta, inténtalo de nuevo.",
        "steam.login.invalid_password_input": "Contraseña incorrecta. Introduce de nuevo: ",
        "steam.login.credentials_missing": "Faltan datos de login.",
        "steam.login.error_generic": "Error al iniciar sesión: {result}",
        "steam.error.no_games": "No hay juegos para iniciar.",
        "steam.interrupt": "Deteniendo...",
        "steam.logout": "[Steam] Sesión cerrada.",
        "steam.warning.persona_missing": "No se encontró el método set_persona.",
    },
    "pt": {
        "menu.banner": "\n╔══════════════════════════════════════╗\n║        ⏰ Steam Hour Booster         ║\n╚══════════════════════════════════════╝",
        "menu.section_main": "[Menu principal]",
        "menu.status": "Conta: {account}   Jogos: {games}",
        "menu.status.account_ok": "ok",
        "menu.status.account_missing": "sem dados",
        "menu.option.account": "Configurar conta",
        "menu.option.games": "Configurar jogos",
        "menu.option.language": "Alterar idioma",
        "menu.option.run": "Iniciar",
        "menu.option.exit": "Sair",
        "prompt.choose_option": "\nEscolha uma opção: ",
        "general.unknown_option": "Opção desconhecida.",
        "general.interrupted_exit": "Interrompido. Encerrando.",
        "general.interrupted_back": "Interrompido. Retornando ao menu.",
        "general.cancelled": "Cancelado.",
        "general.goodbye": "Até logo!",
        "general.back": "Voltar",
        "general.not_set": "[não definido]",
        "general.error": "Erro: {message}",
        "language.initial_title": "Selecione o idioma",
        "language.initial_instruction": "Essa preferência será salva em config.json.",
        "language.prompt": "Digite o número do idioma: ",
        "language.invalid": "Número de idioma inválido.",
        "language.saved": "Idioma salvo: {language}",
        "language.list.entry": "{index}. [{marker}] {label} ({code})",
        "account.menu_banner": "\n╔══════════════════════╗\n║ Conta Steam – menu   ║\n╚══════════════════════╝",
        "account.option.summary": "Mostrar resumo",
        "account.option.username": "Definir login",
        "account.option.password": "Definir senha",
        "account.option.secret": "Definir shared_secret (2FA)",
        "account.option.reset": "Resetar configuração",
        "account.option.language": "Trocar idioma",
        "account.option.api_key": "Definir Steam Web API Key",
        "account.option.steam_id": "Definir SteamID64",
        "account.summary.title": "--- Conta Steam ---",
        "account.summary.login": "Login: {value}",
        "account.summary.password": "Senha: {value}",
        "account.summary.secret": "Shared secret: {value}",
        "account.summary.secret_missing": "não definido",
        "account.prompt.username": "Informe o login Steam: ",
        "account.error.username_required": "O login não pode ficar vazio.",
        "account.saved.username": "Login salvo.",
        "account.prompt.password": "Informe a senha Steam: ",
        "account.error.password_required": "A senha não pode ficar vazia.",
        "account.saved.password": "Senha salva.",
        "account.prompt.secret": "Informe o shared_secret do app móvel (Enter para limpar): ",
        "account.saved.secret": "shared_secret atualizado.",
        "account.error.api_key_required": "A API key não pode ficar vazia.",
        "account.prompt.api_key": "Informe a Steam Web API Key (https://steamcommunity.com/dev/apikey): ",
        "account.saved.api_key": "API key salva.",
        "account.prompt.steam_id": "Informe o SteamID64 (ex. 7656119...): ",
        "account.error.steam_id_required": "SteamID64 é obrigatório.",
        "account.saved.steam_id": "SteamID64 salvo.",
        "account.reset.confirm": "Reset irá remover login/senha. Continuar? ({yes}/N): ",
        "account.reset.done": "Configuração restaurada.",
        "account.language.changed": "Idioma alterado para: {language}",
        "games.menu_banner": "\n╔══════════════════════╗\n║  Jogos – menu        ║\n╚══════════════════════╝",
        "games.option.list": "Listar AppIDs",
        "games.option.add": "Adicionar AppID",
        "games.option.remove": "Remover AppID",
        "games.option.clear": "Limpar lista",
        "games.option.library": "Adicionar da biblioteca",
        "games.summary.empty": "--- Jogos ---\nNenhum AppID configurado.",
        "games.summary.title": "--- Jogos ---",
        "games.summary.count": "Jogos: {count} / {max}",
        "games.summary.items": "AppIDs: {items}",
        "games.error.full": "A lista está cheia.",
        "games.prompt.add": "Informe o AppID (número): ",
        "games.error.appid_integer": "AppID deve ser inteiro.",
        "games.error.appid_positive": "AppID deve ser positivo.",
        "games.error.appid_exists": "AppID já está na lista.",
        "games.added": "AppID adicionado.",
        "games.prompt.remove": "Informe o AppID para remover: ",
        "games.error.appid_missing": "AppID não encontrado.",
        "games.removed": "AppID removido.",
        "games.prompt.clear_confirm": "Deseja remover todos os jogos? ({yes}/N): ",
        "games.cleared": "Lista apagada.",
        "library.fetching": "Buscando biblioteca da Steam...",
        "library.error.credentials": "Preencha a API key nas configurações da conta.",
        "library.prompt.vanity": "Informe o nome do perfil (vanity URL) para obter o SteamID64: ",
        "library.error.vanity_lookup": "Não foi possível obter SteamID: {reason}",
        "library.error.request": "Não foi possível carregar a biblioteca: {reason}",
        "library.empty": "Biblioteca vazia.",
        "library.prompt.selection": "Digite os números (1,3,5) ou Enter para cancelar: ",
        "library.selection.invalid": "Seleção inválida: {value}",
        "library.selection.out_of_range": "Valor fora do intervalo: {value}",
        "library.selection.none": "Nenhum jogo selecionado.",
        "library.added": "{count} jogos adicionados.",
        "library.legend.existing": "[*] Jogo já presente na lista.",
        "library.error.steam_id_missing": "Defina o SteamID64 primeiro.",
        "library.resolved.steam_id": "SteamID64 resolvido: {steam_id}",
        "start.title": "=== ⏰ Iniciando Steam booster ===",
        "start.account": "Conta: {username}",
        "start.games": "Jogos para iniciar: {count}",
        "start.finished": "⏰ Booster parado.",
        "errors.missing_username": "Login não informado.",
        "errors.missing_password": "Senha não informada.",
        "errors.missing_games": "Adicione pelo menos um AppID.",
        "steam.preparing": "[Steam] Preparando {count} jogos: {games}",
        "steam.connecting": "[Steam] Conectando à conta...",
        "steam.launched": "[Steam] Jogos iniciados: {games}",
        "steam.prompt.stop": "⏰ Pressione Enter ou Ctrl+C para parar...\n",
        "steam.running": "⏰ Booster em execução.",
        "steam.clock": "⏰ Tempo total: {time}",
        "steam.login.success": "Login efetuado.",
        "steam.login.email_needed": "[Steam] Código do e-mail necessário.",
        "steam.login.email_prompt": "Código do e-mail: ",
        "steam.login.twofactor_needed": "[Steam] Código do Steam Guard necessário.",
        "steam.login.twofactor_prompt": "Código do app móvel: ",
        "steam.login.invalid_password_prompt": "[Steam] Senha incorreta, tente novamente.",
        "steam.login.invalid_password_input": "Senha incorreta. Digite de novo: ",
        "steam.login.credentials_missing": "Dados de login faltando.",
        "steam.login.error_generic": "Falha no login: {result}",
        "steam.error.no_games": "Nenhum jogo para iniciar.",
        "steam.interrupt": "Parando...",
        "steam.logout": "[Steam] Desconectado.",
        "steam.warning.persona_missing": "set_persona não encontrado.",
    },
    "ru": {
        "menu.banner": "\n╔══════════════════════════════════════╗\n║        ⏰ Steam Hour Booster         ║\n╚══════════════════════════════════════╝",
        "menu.section_main": "[Главное меню]",
        "menu.status": "Аккаунт: {account}   Игры: {games}",
        "menu.status.account_ok": "готов",
        "menu.status.account_missing": "нет данных",
        "menu.option.account": "Настройки аккаунта",
        "menu.option.games": "Настройки игр",
        "menu.option.language": "Изменить язык",
        "menu.option.run": "Запустить",
        "menu.option.exit": "Выход",
        "prompt.choose_option": "\nВыберите пункт: ",
        "general.unknown_option": "Неизвестная опция.",
        "general.interrupted_exit": "Прервано. Выход из программы.",
        "general.interrupted_back": "Прервано. Возврат в меню.",
        "general.cancelled": "Отменено.",
        "general.goodbye": "До встречи!",
        "general.back": "Назад",
        "general.not_set": "[не задано]",
        "general.error": "Ошибка: {message}",
        "language.initial_title": "Выберите язык интерфейса",
        "language.initial_instruction": "Настройка сохранится в config.json.",
        "language.prompt": "Введите номер языка: ",
        "language.invalid": "Неверный номер языка.",
        "language.saved": "Язык сохранён: {language}",
        "language.list.entry": "{index}. [{marker}] {label} ({code})",
        "account.menu_banner": "\n╔══════════════════════╗\n║  Меню аккаунта Steam ║\n╚══════════════════════╝",
        "account.option.summary": "Показать данные",
        "account.option.username": "Задать логин",
        "account.option.password": "Задать пароль",
        "account.option.secret": "Задать shared_secret (2FA)",
        "account.option.reset": "Сбросить конфигурацию",
        "account.option.language": "Изменить язык",
        "account.option.api_key": "Задать Steam Web API Key",
        "account.option.steam_id": "Задать SteamID64",
        "account.summary.title": "--- Аккаунт Steam ---",
        "account.summary.login": "Логин: {value}",
        "account.summary.password": "Пароль: {value}",
        "account.summary.secret": "Shared secret: {value}",
        "account.summary.secret_missing": "не задан",
        "account.prompt.username": "Введите логин Steam: ",
        "account.error.username_required": "Логин не может быть пустым.",
        "account.saved.username": "Логин сохранён.",
        "account.prompt.password": "Введите пароль Steam: ",
        "account.error.password_required": "Пароль не может быть пустым.",
        "account.saved.password": "Пароль сохранён.",
        "account.prompt.secret": "Введите shared_secret из мобильного приложения (Enter для очистки): ",
        "account.saved.secret": "shared_secret обновлён.",
        "account.error.api_key_required": "API key не может быть пустым.",
        "account.prompt.api_key": "Введите Steam Web API Key (https://steamcommunity.com/dev/apikey): ",
        "account.saved.api_key": "API key сохранён.",
        "account.prompt.steam_id": "Введите SteamID64 (например 7656119...): ",
        "account.error.steam_id_required": "Нужно указать SteamID64.",
        "account.saved.steam_id": "SteamID64 сохранён.",
        "account.reset.confirm": "Сброс удалит логин/пароль. Продолжить? ({yes}/N): ",
        "account.reset.done": "Конфигурация сброшена.",
        "account.language.changed": "Язык изменён на: {language}",
        "games.menu_banner": "\n╔══════════════════════╗\n║   Настройка игр      ║\n╚══════════════════════╝",
        "games.option.list": "Показать AppID",
        "games.option.add": "Добавить AppID",
        "games.option.remove": "Удалить AppID",
        "games.option.clear": "Очистить список",
        "games.option.library": "Добавить из библиотеки",
        "games.summary.empty": "--- Игры ---\nСписок пуст.",
        "games.summary.title": "--- Игры ---",
        "games.summary.count": "Игры: {count} / {max}",
        "games.summary.items": "AppID: {items}",
        "games.error.full": "Список игр заполнен.",
        "games.prompt.add": "Введите AppID игры: ",
        "games.error.appid_integer": "AppID должен быть целым числом.",
        "games.error.appid_positive": "AppID должен быть положительным.",
        "games.error.appid_exists": "AppID уже в списке.",
        "games.added": "AppID добавлен.",
        "games.prompt.remove": "Введите AppID для удаления: ",
        "games.error.appid_missing": "AppID не найден.",
        "games.removed": "AppID удалён.",
        "games.prompt.clear_confirm": "Удалить все игры? ({yes}/N): ",
        "games.cleared": "Список игр очищен.",
        "library.fetching": "Загружаю библиотеку Steam...",
        "library.error.credentials": "Укажите API key в настройках аккаунта.",
        "library.prompt.vanity": "Введите имя профиля (vanity URL), чтобы получить SteamID64: ",
        "library.error.vanity_lookup": "Не удалось получить SteamID: {reason}",
        "library.error.request": "Не удалось загрузить библиотеку: {reason}",
        "library.empty": "Библиотека пуста.",
        "library.prompt.selection": "Введите номера (1,3,5) или Enter для отмены: ",
        "library.selection.invalid": "Неверный ввод: {value}",
        "library.selection.out_of_range": "Число вне диапазона: {value}",
        "library.selection.none": "Игры не выбраны.",
        "library.added": "Добавлено игр: {count}.",
        "library.legend.existing": "[*] Игра уже добавлена.",
        "library.error.steam_id_missing": "Сначала укажите SteamID64.",
        "library.resolved.steam_id": "SteamID64 определён: {steam_id}",
        "start.title": "=== ⏰ Запуск Steam booster ===",
        "start.account": "Аккаунт: {username}",
        "start.games": "Игры к запуску: {count}",
        "start.finished": "⏰ Booster остановлен.",
        "errors.missing_username": "Не указан логин.",
        "errors.missing_password": "Не указан пароль.",
        "errors.missing_games": "Добавьте хотя бы один AppID.",
        "steam.preparing": "[Steam] Подготавливаю запуск {count} игр: {games}",
        "steam.connecting": "[Steam] Подключение к аккаунту...",
        "steam.launched": "[Steam] Игры запущены: {games}",
        "steam.prompt.stop": "⏰ Enter или Ctrl+C для остановки...\n",
        "steam.running": "⏰ Booster работает.",
        "steam.clock": "⏰ Общее время: {time}",
        "steam.login.success": "Успешный вход.",
        "steam.login.email_needed": "[Steam] Требуется код из почты.",
        "steam.login.email_prompt": "Код из e-mail: ",
        "steam.login.twofactor_needed": "[Steam] Требуется код из приложения.",
        "steam.login.twofactor_prompt": "Код Steam Guard: ",
        "steam.login.invalid_password_prompt": "[Steam] Неверный пароль, попробуйте снова.",
        "steam.login.invalid_password_input": "Неверный пароль. Введите ещё раз: ",
        "steam.login.credentials_missing": "Не хватает данных для входа.",
        "steam.login.error_generic": "Ошибка входа: {result}",
        "steam.error.no_games": "Нет игр для запуска.",
        "steam.interrupt": "Останавливаю...",
        "steam.logout": "[Steam] Выполнен выход.",
        "steam.warning.persona_missing": "Метод set_persona не найден.",
    },
}


@dataclass
class Localization:
    language: str = DEFAULT_LANGUAGE

    def __post_init__(self) -> None:
        self.set_language(self.language)

    def set_language(self, language: str | None) -> None:
        if language and language in SUPPORTED_LANGUAGES:
            self.language = language
        else:
            self.language = DEFAULT_LANGUAGE

    def translate(self, key: str, **kwargs: object) -> str:
        table = TRANSLATIONS.get(self.language) or TRANSLATIONS[DEFAULT_LANGUAGE]
        template = table.get(key) or TRANSLATIONS[DEFAULT_LANGUAGE].get(key) or key
        return template.format(**kwargs)

    def yes_word(self) -> str:
        return "Y"

    def is_yes(self, value: str) -> bool:
        normalized = value.strip().lower()
        return normalized in {"y", "yes"}

