from __future__ import annotations

from dataclasses import dataclass
from typing import Dict

DEFAULT_LANGUAGE = "pl"

SUPPORTED_LANGUAGES: Dict[str, Dict[str, object]] = {
    "pl": {"label": "Polski", "yes_values": ["tak", "t"]},
    "en": {"label": "English", "yes_values": ["yes", "y"]},
}

TRANSLATIONS: Dict[str, Dict[str, str]] = {
    "pl": {
        "menu.section_main": "[Menu główne]",
        "menu.status": "Konto: {account}   Gry: {games}",
        "menu.status.account_ok": "gotowe",
        "menu.status.account_missing": "brak danych",
        "menu.option.account": "Konfiguracja konta",
        "menu.option.games": "Konfiguracja gier",
        "menu.option.run": "Uruchom",
        "menu.option.exit": "Wyjdź",
        "prompt.choose_option": "\nWybierz opcję: ",
        "general.unknown_option": "Nieznana opcja.",
        "general.interrupted_exit": "Przerwano. Wyłączam program.",
        "general.interrupted_back": "Przerwano. Powrót do menu głównego.",
        "general.cancelled": "Przerwano.",
        "general.goodbye": "Do zobaczenia!",
        "general.back": "Powrót",
        "general.not_set": "[nie ustawiono]",
        "language.initial_title": "Wybierz język interfejsu",
        "language.initial_instruction": "Ta konfiguracja zostanie zapisana w pliku config.json.",
        "language.prompt": "Podaj numer języka: ",
        "language.invalid": "Nieprawidłowy numer języka.",
        "language.saved": "Zapisano język: {language}",
        "account.menu_title": "Konto Steam – menu",
        "account.option.summary": "Podgląd danych",
        "account.option.username": "Ustaw login",
        "account.option.password": "Ustaw hasło",
        "account.option.secret": "Ustaw shared_secret (2FA)",
        "account.option.reset": "Reset całej konfiguracji",
        "account.option.language": "Zmień język interfejsu",
        "account.option.api_key": "Ustaw Steam Web API Key",
        "account.option.steam_id": "Ustaw SteamID64",
        "account.summary.title": "--- Konto Steam ---",
        "account.summary.login": "Login: {value}",
        "account.summary.password": "Hasło: {value}",
        "account.summary.secret": "Shared secret: {value}",
        "account.summary.secret_set": "ustawiono",
        "account.summary.secret_missing": "brak",
        "account.prompt.username": "Podaj login Steam: ",
        "account.error.username_required": "Login nie może być pusty.",
        "account.saved.username": "Zapisano login.",
        "account.prompt.password": "Podaj hasło Steam: ",
        "account.error.password_required": "Hasło nie może być puste.",
        "account.saved.password": "Zapisano hasło.",
        "account.prompt.secret": "Podaj shared_secret z aplikacji mobilnej (Enter aby usunąć): ",
        "account.saved.secret": "Zaktualizowano shared_secret.",
        "account.error.api_key_required": "API key nie może być pusty.",
        "account.prompt.api_key": "Podaj Steam Web API Key (https://steamcommunity.com/dev/apikey): ",
        "account.saved.api_key": "Zapisano API key.",
        "account.prompt.steam_id": "Podaj SteamID64 (np. 76561198...): ",
        "account.error.steam_id_required": "SteamID64 jest wymagane.",
        "account.saved.steam_id": "Zapisano SteamID64.",
        "account.reset.confirm": "Reset usunie login/hasło. Kontynuować? ({yes}/N): ",
        "account.reset.done": "Przywrócono domyślną konfigurację.",
        "account.language.changed": "Zmieniono język na: {language}",
        "games.menu_title": "Gry – konfiguracja",
        "games.option.list": "Lista AppID",
        "games.option.add": "Dodaj AppID gry",
        "games.option.remove": "Usuń AppID gry",
        "games.option.clear": "Wyczyść listę gier",
        "games.option.library": "Dodaj z biblioteki Steam",
        "games.summary.empty": "--- Gry ---\nBrak dodanych AppID.",
        "games.summary.title": "--- Gry ---",
        "games.summary.count": "Liczba gier: {count} / {max}",
        "games.summary.items": "AppID-y: {items}",
        "games.list.current_none": "Brak dodanych AppID.",
        "games.list.current": "Aktualne AppID: {items}",
        "games.error.full": "Lista gier jest pełna.",
        "games.prompt.add": "Podaj AppID gry (liczba): ",
        "games.error.appid_integer": "AppID musi być liczbą całkowitą.",
        "games.error.appid_positive": "AppID musi być dodatnie.",
        "games.error.appid_exists": "AppID już znajduje się na liście.",
        "games.added": "Dodano AppID.",
        "games.prompt.remove": "Podaj AppID do usunięcia: ",
        "games.error.appid_missing": "AppID nie znajduje się na liście.",
        "games.removed": "Usunięto AppID.",
        "games.prompt.clear_confirm": "Na pewno chcesz usunąć wszystkie gry? ({yes}/N): ",
        "games.cleared": "Wyczyszczono listę gier.",
        "library.fetching": "Pobieram bibliotekę gier ze Steam...",
        "library.error.credentials": "Uzupełnij API key (https://steamcommunity.com/dev/apikey) w konfiguracji konta.",
        "library.prompt.vanity": "Podaj nazwę profilu Steam (vanity URL), aby automatycznie pobrać SteamID64: ",
        "library.error.vanity_lookup": "Nie udało się ustalić SteamID na podstawie nazwy: {reason}",
        "library.error.request": "Nie udało się pobrać listy gier: {reason}",
        "library.empty": "Biblioteka gier jest pusta.",
        "library.prompt.selection": "Podaj numery gier do dodania (np. 1,3,5) lub Enter aby anulować: ",
        "library.selection.invalid": "Nieprawidłowy wybór: {value}",
        "library.selection.none": "Nie wybrano żadnej gry.",
        "library.added": "Dodano z biblioteki: {count} gier.",
        "start.title": "=== ⏰ Start programu Steam ===",
        "start.account": "Konto: {username}",
        "start.games": "Gry do uruchomienia: {count}",
        "start.finished": "⏰ Booster zatrzymany.",
        "errors.missing_username": "Brakuje nazwy użytkownika Steam.",
        "errors.missing_password": "Brakuje hasła Steam.",
        "errors.missing_games": "Dodaj co najmniej jeden AppID gry.",
        "steam.preparing": "[Steam] Przygotowuję uruchomienie {count} gier: {games}",
        "steam.connecting": "[Steam] Łączenie z kontem...",
        "steam.launched": "[Steam] Uruchomiono gry: {games}",
        "steam.prompt.stop": "⏰ Wciśnij Enter lub Ctrl+C, aby zatrzymać program...\n",
        "steam.running": "⏰ Booster działa.",
        "steam.clock": "⏰ Nabity łączny czas: {time}",
        "steam.login.success": "Pomyślnie zalogowano.",
        "steam.login.email_needed": "[Steam] Wymagany kod z e-mail (Steam Guard).",
        "steam.login.email_prompt": "Kod z e-mail (Steam Guard): ",
        "steam.login.twofactor_needed": "[Steam] Wymagany kod z aplikacji Steam Guard.",
        "steam.login.twofactor_prompt": "Kod z aplikacji mobilnej Steam: ",
        "steam.login.invalid_password_prompt": "[Steam] Błędne hasło, spróbuj ponownie.",
        "steam.login.invalid_password_input": "Błędne hasło. Podaj ponownie: ",
        "steam.login.credentials_missing": "Brakuje danych logowania.",
        "steam.login.error_generic": "Logowanie zakończone błędem: {result}",
        "steam.error.no_games": "Brak gier do uruchomienia.",
        "steam.interrupt": "Przerywam...",
        "steam.logout": "[Steam] Wylogowano ze Steam.",
        "steam.warning.persona_missing": "Nie znaleziono metody set_persona w kliencie Steam.",
    },
    "en": {
        "menu.section_main": "[Main menu]",
        "menu.status": "Account: {account}   Games: {games}",
        "menu.status.account_ok": "ready",
        "menu.status.account_missing": "missing",
        "menu.option.account": "Account configuration",
        "menu.option.games": "Games configuration",
        "menu.option.run": "Run",
        "menu.option.exit": "Exit",
        "prompt.choose_option": "\nChoose an option: ",
        "general.unknown_option": "Unknown option.",
        "general.interrupted_exit": "Interrupted. Exiting program.",
        "general.interrupted_back": "Interrupted. Returning to main menu.",
        "general.cancelled": "Cancelled.",
        "general.goodbye": "See you!",
        "general.back": "Back",
        "general.not_set": "[not set]",
        "language.initial_title": "Select interface language",
        "language.initial_instruction": "This preference will be saved inside config.json.",
        "language.prompt": "Enter language number: ",
        "language.invalid": "Invalid language number.",
        "language.saved": "Language saved: {language}",
        "account.menu_title": "Steam account – menu",
        "account.option.summary": "Show summary",
        "account.option.username": "Set login",
        "account.option.password": "Set password",
        "account.option.secret": "Set shared_secret (2FA)",
        "account.option.reset": "Reset entire configuration",
        "account.option.language": "Change interface language",
        "account.option.api_key": "Set Steam Web API Key",
        "account.option.steam_id": "Set SteamID64",
        "account.summary.title": "--- Steam account ---",
        "account.summary.login": "Login: {value}",
        "account.summary.password": "Password: {value}",
        "account.summary.secret": "Shared secret: {value}",
        "account.summary.secret_set": "set",
        "account.summary.secret_missing": "not set",
        "account.prompt.username": "Enter Steam login: ",
        "account.error.username_required": "Login cannot be empty.",
        "account.saved.username": "Login saved.",
        "account.prompt.password": "Enter Steam password: ",
        "account.error.password_required": "Password cannot be empty.",
        "account.saved.password": "Password saved.",
        "account.prompt.secret": "Enter shared_secret from the mobile app (press Enter to clear): ",
        "account.saved.secret": "shared_secret updated.",
        "account.error.api_key_required": "API key cannot be empty.",
        "account.prompt.api_key": "Enter Steam Web API Key (https://steamcommunity.com/dev/apikey): ",
        "account.saved.api_key": "API key saved.",
        "account.prompt.steam_id": "Enter SteamID64 (e.g. 76561198...): ",
        "account.error.steam_id_required": "SteamID64 is required.",
        "account.saved.steam_id": "SteamID64 saved.",
        "account.reset.confirm": "Reset will remove login/password. Continue? ({yes}/N): ",
        "account.reset.done": "Configuration restored to defaults.",
        "account.language.changed": "Interface language changed to: {language}",
        "games.menu_title": "Games – configuration",
        "games.option.list": "List AppIDs",
        "games.option.add": "Add a game AppID",
        "games.option.remove": "Remove a game AppID",
        "games.option.clear": "Clear the list",
        "games.option.library": "Add from Steam library",
        "games.summary.empty": "--- Games ---\nNo AppIDs configured.",
        "games.summary.title": "--- Games ---",
        "games.summary.count": "Games: {count} / {max}",
        "games.summary.items": "AppIDs: {items}",
        "games.list.current_none": "No AppIDs configured.",
        "games.list.current": "Current AppIDs: {items}",
        "games.error.full": "The list of games is full.",
        "games.prompt.add": "Enter the game AppID (number): ",
        "games.error.appid_integer": "AppID must be an integer.",
        "games.error.appid_positive": "AppID must be positive.",
        "games.error.appid_exists": "AppID is already on the list.",
        "games.added": "AppID added.",
        "games.prompt.remove": "Enter the AppID to remove: ",
        "games.error.appid_missing": "AppID was not found on the list.",
        "games.removed": "AppID removed.",
        "games.prompt.clear_confirm": "Do you really want to remove all games? ({yes}/N): ",
        "games.cleared": "Game list cleared.",
        "library.fetching": "Fetching your Steam library...",
        "library.error.credentials": "Please fill in your API key (https://steamcommunity.com/dev/apikey) in the account settings.",
        "library.prompt.vanity": "Enter your Steam profile name (vanity URL) to resolve SteamID64: ",
        "library.error.vanity_lookup": "Failed to resolve SteamID from profile name: {reason}",
        "library.error.request": "Failed to fetch games: {reason}",
        "library.empty": "Your library is empty.",
        "library.prompt.selection": "Enter numbers to add (e.g. 1,3,5) or press Enter to cancel: ",
        "library.selection.invalid": "Invalid selection: {value}",
        "library.selection.none": "No games selected.",
        "library.added": "Added {count} games from the library.",
        "start.title": "=== ⏰ Starting Steam booster ===",
        "start.account": "Account: {username}",
        "start.games": "Games to launch: {count}",
        "start.finished": "⏰ Booster stopped.",
        "errors.missing_username": "Steam login is missing.",
        "errors.missing_password": "Steam password is missing.",
        "errors.missing_games": "Add at least one AppID.",
        "steam.preparing": "[Steam] Preparing to launch {count} games: {games}",
        "steam.connecting": "[Steam] Connecting to the account...",
        "steam.launched": "[Steam] Games launched: {games}",
        "steam.prompt.stop": "⏰ Press Enter or Ctrl+C to stop the program...\n",
        "steam.running": "⏰ Booster is running.",
        "steam.clock": "⏰ Total accumulated time: {time}",
        "steam.login.success": "Logged in successfully.",
        "steam.login.email_needed": "[Steam] E-mail (Steam Guard) code required.",
        "steam.login.email_prompt": "Steam Guard e-mail code: ",
        "steam.login.twofactor_needed": "[Steam] Steam Guard mobile code required.",
        "steam.login.twofactor_prompt": "Steam Guard mobile code: ",
        "steam.login.invalid_password_prompt": "[Steam] Wrong password, try again.",
        "steam.login.invalid_password_input": "Wrong password. Enter again: ",
        "steam.login.credentials_missing": "Login data is missing.",
        "steam.login.error_generic": "Login failed with error: {result}",
        "steam.error.no_games": "No games to launch.",
        "steam.interrupt": "Stopping...",
        "steam.logout": "[Steam] Logged out.",
        "steam.warning.persona_missing": "Could not find set_persona method in Steam client.",
    },
}


@dataclass
class Localization:
    language: str = DEFAULT_LANGUAGE

    def __post_init__(self) -> None:
        self.set_language(self.language)

    def set_language(self, language: str | None) -> None:
        if language and language in SUPPORTED_LANGUAGES:
            self.language = language
        else:
            self.language = DEFAULT_LANGUAGE

    def translate(self, key: str, **kwargs: object) -> str:
        table = TRANSLATIONS.get(self.language) or TRANSLATIONS[DEFAULT_LANGUAGE]
        template = table.get(key) or TRANSLATIONS[DEFAULT_LANGUAGE].get(key) or key
        return template.format(**kwargs)

    def yes_word(self) -> str:
        meta = SUPPORTED_LANGUAGES.get(self.language) or SUPPORTED_LANGUAGES[DEFAULT_LANGUAGE]
        return str(meta["yes_values"][0])

    def is_yes(self, value: str) -> bool:
        meta = SUPPORTED_LANGUAGES.get(self.language) or SUPPORTED_LANGUAGES[DEFAULT_LANGUAGE]
        normalized = value.strip().lower()
        return normalized in (meta.get("yes_values") or [])

